name: front-ci

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  front-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0
          
      - run: pnpm i --frozen-lockfile
      - run: pnpm build:shared
      - run: pnpm build:app
